name: Publish NuGet Packages

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build --configuration Release -warnaserror

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test --configuration Release -warnaserror

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pack
      run: |
        VERSION=`echo ${GITHUB_REF} | perl -pe 's/^refs\/tags\/(.*)$/\1/'`
        FILE_VERSION=`echo ${GITHUB_REF} | perl -pe 's/^refs\/tags\/(\d+(?:\.\d+)*)(.*)$/\1/'`
        dotnet pack --configuration Release --output packages -p:Version=$VERSION -p:FileVersion=$FILE_VERSION
    - name: Upload NuGet package artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'packages/*.nupkg'
    - name: Publish
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY_4 }} --source https://api.nuget.org/v3/index.json